data:
  raw_path: "data/raw/"
  processed_path: "data/processed/"

model:
  name: "AdaBoost"
  test_size: 0.2
  random_state: 42
  threshold: 0.5

training:
  use_smote: true
  scale_data: true

flask:
  host: "0.0.0.0"
  port: 5000
  debug: true
